# Generated by Django 5.2.8 on 2025-11-21 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(default='python', max_length=50)),
                ('code', models.TextField()),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm_model', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('issues', models.JSONField(blank=True, null=True)),
                ('suggestions', models.JSONField(blank=True, null=True)),
                ('tests_suggestions', models.TextField(blank=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.submission')),
            ],
        ),
    ]
