# Generated by Django 5.2.8 on 2025-11-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='file_path',
            field=models.CharField(blank=True, help_text='Path of file inside project for ZIP uploads', max_length=255),
        ),
    ]
